name = "ShockwaveDetection"
uuid = "a75b99cc-be56-4638-99bc-d89fa43b9ca1"
authors = ["Warisa <compund555@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
